// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.openqa.selenium.devtools.v112.page.Page.navigate;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class SeleniumTest1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();  // provides a way to share data or pass information between different parts of the test
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void hongik5() throws InterruptedException {
        driver.get("https://www.hongik.ac.kr/index.do");
        driver.manage().window().setSize(new Dimension(1760, 1061));
        driver.findElement(By.linkText("대학소개")).click();
        driver.findElement(By.linkText("대학/대학원")).click();
        driver.findElement(By.linkText("학사지원")).click();
        driver.findElement(By.cssSelector(".vp > .logo > img")).click();
        Thread.sleep(1000);

        driver.navigate().to("https://www.naver.com");
        Thread.sleep(1000);
        driver.findElement(By.id("query")).click();
        driver.findElement(By.id("query")).sendKeys("a");
        driver.findElement(By.id("query")).sendKeys(Keys.ENTER);
        //Thread.sleep(1000);
        //driver.findElement(By.cssSelector(".ico_logo")).click();
        Thread.sleep(1000);
        Thread.sleep(1000);
/*
        driver.navigate().to("https://www.daum.net");
        Thread.sleep(1000);
        driver.findElement(By.linkText("증권")).click();
        Thread.sleep(1000);
        driver.findElement(By.linkText("국내")).click();
        Thread.sleep(1000);
        driver.findElement(By.linkText("뉴스")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("minidaum")).click();
        Thread.sleep(1000);
        driver.findElement(By.linkText("Daum")).click();
        Thread.sleep(1000);
        */
        driver.close();
    }
}

